services:
  web:
    build: .
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8000"]
      interval: 5s
      retries: 5
    networks:
      - network
    depends_on:
       redis:
         condition: service_healthy
       db:
         condition: service_healthy
    volumes:
      - ./src:/app/src

  celery:
    build: .
    command: celery -A src.works.main worker -l info
    networks:
      - network
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/dumps:/app/dumps

  celery-beat:
    build: .
    command: celery -A src.works.main:app beat -l info
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/dumps:/app/dumps

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    networks:
      - network

  db:
    image: postgres:14.1
#    ports:
#      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d autos"]
      interval: 5s
      retries: 5
    networks:
      - network
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: autos
      POSTGRES_PASSWORD: password

networks:
  network:
    driver: bridge
